<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name = "base_xacro" params="length radius">
        <link name="base_footprint" />

            
        



            <!-- 机器人身体的部分-->
        <link name="base_link">
            <visual>
                <!-- 沿着自己几何中心的偏移量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                <!-- 这是一个圆柱体，半径为10cm，高度为12cm -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 这是材质和颜色的描述 -->
                <material name="white"> 
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
        
        </link>
        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
            
        </joint> 
    </xacro:macro>
</robot>
